[build]
  publish = "site"
  # https://docs.netlify.com/configure-builds/ignore-builds/
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF netlify.toml mkdocs.yml requirements.txt ./docs/"
  command = "mkdocs build"

[[headers]]
  # Relax cross origin restrictions for schemas, so they can be requested by front-end apps.
  for = "/schema/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"